// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smofakvxhjbeyaqcppfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtb2Zha3Z4aGpiZXlhcWNwcGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODAxMTUsImV4cCI6MjA2MDU1NjExNX0.zUIdZlT_8esRLhDl6aQY7Ohs3cgsFa9DhA5cV7nkXuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);